name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Verify Railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway whoami || echo "Railway authentication failed"

      - name: Run migrations (optional)
        run: |
          echo "Running pre-deploy migrations..."
          npm run migrate || echo "No migrations found"

      - name: Deploy to Railway (non-interactive)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Starting Railway deploy..."
          railway up --service jubilant-smile --environment production --detach --yes
          echo "✅ Deployment completed."

      - name: Start application
        run: |
          npm run start
