name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Verify Railway login
        run: railway whoami || true

      - name: Deploy to Railway
        run: |
          echo "Starting Railway deploy..."
          railway up --service jubilant-smile --project ${{ secrets.RAILWAY_PROJECT_ID }} --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Post Setup Node.js
        run: echo "Deployment completed successfully!"
