name: Full DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cinescope-app:latest .

      # ✅ Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cinescope-app:latest

  terraform-deploy:
    name: Apply Terraform (Deploy)
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Validate Terraform
        run: terraform -chdir=terraform validate

      # ✅ Deploy with Terraform
      - name: Apply Terraform (Deploy)
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform apply -auto-approve \
            -var "dockerhub_user=${{ secrets.DOCKER_USERNAME }}" \
            -var "dockerhub_pass=${{ secrets.DOCKER_PASSWORD }}"

  post-setup:
    name: Post Set up Docker
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
      - name: Confirm deployment
        run: echo "✅ Deployment successful — Terraform and Docker completed."
