name: Terraform Deploy

on:
  workflow_dispatch:  # allows manual run from GitHub Actions tab

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker (for Docker provider)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker --version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve
