name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Verify Docker installation
      - name: Verify Docker Installation
        run: |
          docker --version
          docker info

      # ✅ Pull Docker image (correct username)
      - name: Pull Docker image
        run: |
          docker pull samj4/devops-node-aks:latest
          docker images

      # ✅ Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # ✅ Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      # ✅ Apply Terraform
      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve
