name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Docker is preinstalled — just check it instead of reinstalling
      - name: Verify Docker Installation
        run: |
          docker --version
          docker info

      # ✅ Pull your image from Docker Hub
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-node-aks:latest
          docker images

      # ✅ Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve
